In [1]:
# # !python --version
# # !pip install --force-reinstall torch==2.3.1 torchtext=0.18.0
# !rm -rf /kaggle/working/DL-BHW-2
# # import torchtext

# from kaggle_secrets import UserSecretsClient
# user_secrets = UserSecretsClient()
# GITHUB_TOKEN = user_secrets.get_secret("github_token")
# USER = "git"
# CLONE_URL = f"https://{USER}:{GITHUB_TOKEN}@github.com/chagrygoris/DL-BHW-2.git"
# wandb_api_key = user_secrets.get_secret("wandb_api_key")
# get_ipython().system(f"git clone -b main {CLONE_URL}")


In [2]:
# import sys
# sys.path.append("/kaggle/working/DL-BHW-2/src")
# PAHT_TO_DATA = "/kaggle/working/DL-BHW-2/data"
PATH_TO_DATA = "../data"
OUTPUT_PATH = "./predictions.txt"

In [3]:
from train_routine import create_dataloaders
from tqdm import tqdm
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchtext
torchtext.disable_torchtext_deprecation_warning()


# device = torch.device("cuda")
device = torch.device("mps")
train_loader, val_loader, test_loader = create_dataloaders(path_to_data=PATH_TO_DATA, batch_size=64, device=device)

(tensor([   2, 1337,    0,   27,    9,   12, 1930,  354,    5,   10,  126, 9304,
           0,    5,    3,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1]), 15)
(tensor([   2, 1378,    0,   56,   19,   17, 1340,    0,    5,   12,   85, 7433,
           0,    5,    3,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1, 

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
import sacrebleu
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [172]:
%reload_ext autoreload
%autoreload 2

from transformer_model import build_transformer

model = build_transformer(
    src_vocab_size=train_loader.dataset.de.vocab_size,
    tgt_vocab_size=train_loader.dataset.en.vocab_size,
    src_seq_len=80,
    tgt_seq_len=80,
    d_model=256,
    N=3,
    h=8,
    dropout=0.1,
    d_ff=512
)

In [175]:
train_loader.dataset.en.vocab_size

19057

In [177]:
device = "cpu"
dummy = torch.randint(32, (32, 80)).to(device)
dummy_mask = torch.ones(32, 80).unsqueeze(1).unsqueeze(1).to(device)

out = model.encode(dummy, dummy_mask)
out = model.decode(encoder_output=out, src_mask=dummy_mask, tgt=dummy, tgt_mask=dummy_mask)
out = model.project(out)
out.shape

torch.Size([256, 19057])
torch.Size([32, 80, 256])


torch.Size([32, 80, 19057])

In [178]:
src, srclen, tgt, tgtlen = next(iter(train_loader))

In [180]:
from torch.utils.data import DataLoader



loader = DataLoader(train_loader.dataset, batch_size=8, collate_fn=lambda batch : collate_fn(batch, device="mps"))


In [181]:
batch = next(iter(loader))

In [182]:
print(batch["tgt_mask"][0][0].shape)
print(batch["label"].shape)

torch.Size([35, 35])


KeyError: 'label'

In [183]:
from train_routine import create_dataloaders_tf

loader, _, _ = create_dataloaders_tf(batch_size=64, device="mps")

batch = next(iter(loader))

model.to("mps")

out = model.encode(batch["src"], batch["src_mask"])
out = model.decode(encoder_output=out, src_mask=batch["src_mask"], tgt=batch["tgt"], tgt_mask=batch["tgt_mask"])
out = model.project(out)
out.shape

(tensor([   2, 1337,    0,   27,    9,   12, 1930,  354,    5,   10,  126, 9304,
           0,    5,    3,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1]), 15)
(tensor([   2, 1378,    0,   56,   19,   17, 1340,    0,    5,   12,   85, 7433,
           0,    5,    3,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1, 

torch.Size([64, 51, 19057])