In [1]:
# # !python --version
# # !pip install --force-reinstall torch==2.3.1 torchtext=0.18.0
# !rm -rf /kaggle/working/DL-BHW-2
# # import torchtext

# from kaggle_secrets import UserSecretsClient
# user_secrets = UserSecretsClient()
# GITHUB_TOKEN = user_secrets.get_secret("github_token")
# USER = "git"
# CLONE_URL = f"https://{USER}:{GITHUB_TOKEN}@github.com/chagrygoris/DL-BHW-2.git"
# wandb_api_key = user_secrets.get_secret("wandb_api_key")
# get_ipython().system(f"git clone -b main {CLONE_URL}")


In [10]:
# import sys
# sys.path.append("/kaggle/working/DL-BHW-2/src")
# PAHT_TO_DATA = "/kaggle/working/DL-BHW-2/data"
PATH_TO_DATA = "../data"
OUTPUT_PATH = "./predictions.txt"

In [39]:
from train_routine import create_dataloaders
from tqdm import tqdm
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchtext
torchtext.disable_torchtext_deprecation_warning()


device = torch.device("cuda")
train_loader, val_loader, test_loader = create_dataloaders(path_to_data=PATH_TO_DATA, batch_size=64, device=device)

(tensor([   2, 1337,    0,   27,    9,   12, 1930,  354,    5,   10,  126, 9304,
           0,    5,    3,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1]), 15)
(tensor([   2, 1378,    0,   56,   19,   17, 1340,    0,    5,   12,   85, 7433,
           0,    5,    3,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1]), 15)
(tensor([    2,    37,    10,  1579,   139,   532,    41,     4,    88,    10,
          113,  1638,    20,    23, 13527, 11939,  1245, 10245,     5,     3,
            1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1]), 20)
(tensor([   2,   59,   12,   23, 1073,    4,   12,  371, 7372,   68,   43,  704,
           8,    6,  519,    9, 1917,   13,   45,  512,    5,    3,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1]

In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
import sacrebleu
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [83]:
###---one more try---###
import torch.nn as nn
import torch
class Encoder(nn.Module):
    def __init__(self, dataset, hidden_dim=256):
        super().__init__()
        self.dataset = dataset
        self.hidden_dim = hidden_dim
        self.embed = nn.Embedding(dataset.vocab_size, hidden_dim, padding_idx=dataset.pad_token)
        self.rnn = nn.GRU(hidden_dim, hidden_dim, bidirectional=True, batch_first=True)

    def forward(self, x):
        x = self.embed(x)
        output, hidden = self.rnn(x)
        return output, hidden

class BahdanauAttention(nn.Module):
    # following original naming from Bahdanau
    def __init__(self, enc_output_dim=128, ffn_dim=256):
        super().__init__()
        # alignment model a(x) - FFN
        self.a = nn.Sequential(
            nn.Linear(2 * enc_output_dim + enc_output_dim, ffn_dim),
            nn.Tanh(),
            nn.Linear(ffn_dim, 1)
        )
        self.softmax = nn.Softmax(dim=1)

    def forward(self, h, s, mask):
        # h - encoder outputs / annotations for german sequence of shape (B, T_x, H)
        # s - previous hidden state of decoder of shape (B, 1, H)
        # mask - boolean of shape (B, T_x, 1)
        s = s.expand(s.size(0), h.size(1), s.size(2)) # also (B, T_x, H)
        x = torch.cat((h, s), dim=-1) # (B, T_x, 2 * H)
        e = self.a(x) # (B, T_x, 1)
        alpha = self.softmax(e.masked_fill(mask, -1e9)) # (B, T_x, 1)
        # return torch.bmm(alpha.permute(0, 2, 1), h)
        return alpha.permute(0, 2, 1) @ h

class Decoder(nn.Module):
    def __init__(self, dataset, hidden_dim=256, enc_output_dim=256):
        super().__init__()
        self.embed = nn.Embedding(dataset.vocab_size, hidden_dim, padding_idx=dataset.pad_token)
        self.rnn = nn.GRU(hidden_dim + 2 * enc_output_dim, hidden_dim, bidirectional=False, batch_first=True)
        self.attention = BahdanauAttention(hidden_dim)
        self.lm_head = nn.Linear(hidden_dim, dataset.vocab_size)


    def forward(self, h, s, y, mask):
        # h - annotations of shape (B, T_x, H)
        # s - previous hidden state of shape (B, 1, H)
        # y - input tokens of shape (B, 1)
        # mask - (B, 1, T_x)
        y = self.embed(y).unsqueeze(1) # (B, 1, H)
        c = self.attention(h, s, mask) # context vectors of shape (B, 1, H)
        y, s = self.rnn(torch.cat((y, c), dim=-1), s.permute(1, 0, 2)) # (B, 1, H), (1, B, H)
        y = self.lm_head(y)
        return y, s.permute(1, 0, 2)

class EncoderDecoder(nn.Module):
    def __init__(self, dataset, hidden_dim=256):
        super().__init__()
        self.dataset = dataset
        self.encoder = Encoder(dataset.de, hidden_dim=hidden_dim)
        self.decoder = Decoder(dataset.en, hidden_dim=hidden_dim, enc_output_dim=hidden_dim)
        self.proj = nn.Linear(2 * hidden_dim, hidden_dim)

    def forward(self, deutsch, english, teacher_forcing_rate=0.5):
        logits = []
        mask = (deutsch == self.dataset.de.pad_token).unsqueeze(2)
        h, s = self.encoder(deutsch)
        s = torch.cat((s[0], s[1]), dim=-1).unsqueeze(1)
        s = self.proj(s)
        y = english[:, 0]
        for i in range(1, english.size(1)):
            y, s = self.decoder(h, s, y, mask)
            logits.append(y)
            if torch.rand((1,)).item() < teacher_forcing_rate:
                y = english[:, i]
            else:
                y = y.argmax(dim=-1).squeeze(1)
        return torch.cat(logits, dim=1)

    def inference(self, deutsch, device=torch.device("cpu"), max_seq_len=40):
        generated = []
        mask = (deutsch == self.dataset.de.pad_token).unsqueeze(2)
        h, s = self.encoder(deutsch)
        s = torch.cat((s[0], s[1]), dim=-1).unsqueeze(1)
        s = self.proj(s)
        y = torch.empty((deutsch.size(0), ), dtype=torch.long).fill_(self.dataset.en.bos_token).to(device)
        for i in range(1, max_seq_len):
            y, s = self.decoder(h, s, y, mask)
            y = y.argmax(dim=-1)
            generated.append(y)
            y = y.squeeze(1)
        return torch.cat(generated, dim=1)

attn = BahdanauAttention()
dec = Decoder(train_loader.dataset.en)
dummy_h = torch.rand(64, 80, 256)
dummy_s = torch.rand(64, 1, 256)
dummy_mask = torch.ones(64, 80, 1)
dummy_y = torch.ones(64, 1, dtype=torch.long)

# attn(dummy_h, dummy_s, dummy_mask).shape
# dec(dummy_h, dummy_s, dummy_y, dummy_mask)


model = EncoderDecoder(train_loader.dataset, hidden_dim=256).to(device)
de, delen, en, enlen = next(iter(train_loader))
model(de, en).shape

torch.Size([32, 34, 19057])

In [84]:
def train_epoch(model, loader, opt, crit):
    model.train()
    total = 0
    for src, sl, trg, tl in tqdm(loader):
        src, trg = src.to(device), trg.to(device)
        opt.zero_grad()
        out = model(src, trg)
        # out = out[:, 1:].reshape(-1, out.size(-1))
        # trg = trg[:, 1:].reshape(-1)
        loss = crit(out.transpose(1, 2), trg[:, 1:])
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1)
        opt.step()
        total += loss.item()
    return total / len(loader)

optimizer = torch.optim.Adam(model.parameters())
criterion = nn.CrossEntropyLoss(ignore_index=train_loader.dataset.en.pad_token)
trained = train_epoch(model, train_loader, optimizer, criterion)
trained

100%|██████████| 6123/6123 [11:02<00:00,  9.24it/s]


4.503259379042532

In [85]:
# torch.save(model.state_dict(), "/kaggle/working/DL-BHW-2/model.pth")
import sacrebleu
def evaluate(model, loader, crit, vocab):
    model.eval()
    loss_total = 0
    refs, hyps = [], []

    with torch.no_grad():
        for src, sl, trg, tl in loader:
            src, trg = src.to(device), trg.to(device)
            out = model(src, trg, 0)
            loss = crit(out.transpose(1, 2), trg[:, 1:])
            loss_total += loss.item()

            pred = model.inference(src, device).cpu().tolist()
            trg = trg.cpu().tolist()

            for p, t in zip(pred, trg):
                hyp = vocab.lookup_tokens([i for i in p if i > 3])
                ref = vocab.lookup_tokens([i for i in t if i > 3])
                hyps.append(" ".join(hyp))
                refs.append(" ".join(ref))

    bleu = sacrebleu.corpus_bleu(hyps, [refs]).score
    return loss_total / len(loader), bleu

# model = EncoderDecoder(train_loader.dataset, hidden_dim=256).to(device)
# model.load_state_dict(torch.load("/kaggle/working/DL-BHW-2/model.pth"))
model.to(device)
evaluate(model, val_loader, criterion, train_loader.dataset.en.vocab)

That's 100 lines that end in a tokenized period ('.')
It looks like you forgot to detokenize your test data, which may hurt your score.
If you insist your data is detokenized, or don't care, you can suppress this message with the `force` parameter.


(4.715976376687327, 13.054843491642485)

In [86]:
def predict_test(model, test_loader, en_vocab, max_len=40, device=None):
    import torch
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device).eval()
    eos_idx = en_vocab["<eos>"]
    bos_idx = en_vocab["<bos>"]
    pad_idx = en_vocab["<pad>"]
    preds = []
    with torch.no_grad():
        for batch in test_loader:
            src = batch[0].to(device)
            out_ids = model.inference(src, max_seq_len=max_len, device=device).cpu().tolist()
            for seq in out_ids:
                toks = []
                for idx in seq:
                    if idx == eos_idx:
                        break
                    if idx == bos_idx or idx == pad_idx:
                        continue
                    toks.append(en_vocab.lookup_tokens([idx])[0])
                preds.append(" ".join(toks))
    return preds
test_predictions = predict_test(model.to(device), test_loader, train_loader.dataset.en.vocab)

for p in test_predictions[:5]:
    print(p)

and that worked .
and in the next eight eight , eight days , nine days , , they said , the <unk> .
thank you .
now , we 've got a <unk> <unk> " <unk> , which people people who are always for for the , , for the , , you know , you know ,
we we a a mistake that we so we a a a to a patient .


In [87]:
with open(OUTPUT_PATH, "w") as f:
    for i in range(len(test_predictions)):
        print(test_predictions[i], file=f)